name: 'build tools setup action'
inputs:
  os:
    description: 'os'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Python
      if: needs.check-src.outputs.status
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
      
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 'stable'

    - name: install dependencies
      shell: bash
      if: inputs.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev