[package]
name = "SOEMAUTDServer"
version = "21.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"

description = "AUTDServer"
repository = "https://github.com/shinolab/autd3-server"
readme = "../README.md"
keywords = ["autd"]

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
autd3-protobuf = { version = "21.0.0", features = ["lightweight"] }
autd3-link-soem = { version = "21.0.0" }
autd3-driver = { version = "21.0.0" }
anyhow = "1.0.72"
ctrlc = "3.3.0"
tonic = "0.10.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
chrono = "0.4.31"
tracing-core = "0.1.32"
